apiVersion: 1

datasources:
  # Prometheus para métricas
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: '15s'
      queryTimeout: '60s'
      httpMethod: POST

  # Loki para logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        # Conecta logs com traces usando trace_id
        - datasourceUid: Jaeger
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: '$${__value.raw}'

  # Jaeger para traces
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogs:
        # Conecta traces com logs
        datasourceUid: 'Loki'
        tags: ['service', 'trace_id']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: true
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
      nodeGraph:
        enabled: true

  # PostgreSQL (opcional, para consultas diretas)
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: app_database
    user: admin
    secureJsonData:
      password: admin123
    editable: true
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400